name: DangerNode's Cyber Security Blog
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-cayman
baseurl: ""
url: "https://dangernode.github.io/"
twitter_username: DangerNode
github_username: DangerNode