# Site settings
title: DangerNode's Cyber Security Blog
description: > 
  A cyber security blog. 
# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: minima
baseurl: ""
url: "https://dangernode.github.io"
twitter_username: DangerNode
github_username: DangerNode